name: build

on: [push,pull_request]

jobs:
  build:

    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.4"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Installing PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        ini-values: memory_limit=-1

    - name: "Install composer dependencies"
      uses: "ramsey/composer-install@v3"

    - name: Run test suite
      run: PHP_CS_FIXER_IGNORE_ENV=1 composer build
